export const GET_CART = "GET_CART";
export const INCREASE_QTY_IN_CART = "INCREASE_QTY_IN_CART";
export const DECREASE_QTY_IN_CART = "DECREASE_QTY_IN_CART";
export const ADDED_TO_CART = "ADDED_TO_CART";
export const EMPTY_OUT_CART = "EMPTY_OUT_CART";
export const REMOVED_FROM_CART = "REMOVED_FROM_CART";
export const GET_PRODUCTS = "GET_PRODUCTS";
